"""Initial migration with Todo, Question, Answer tables

Revision ID: 856eafb0a13e
Revises:
Create Date: 2025-11-12 03:03:01.967935

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '856eafb0a13e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'question',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('subject', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('creator_ip', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_question_creator_ip'), 'question', ['creator_ip'], unique=False
    )
    op.create_index(
        op.f('ix_question_deleted_at'), 'question', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_table(
        'todo',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('task', sa.String(), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('creator_ip', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_todo_creator_ip'), 'todo', ['creator_ip'], unique=False)
    op.create_index(op.f('ix_todo_deleted_at'), 'todo', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    op.create_table(
        'answer',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('creator_ip', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('question_id', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['answer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_answer_creator_ip'), 'answer', ['creator_ip'], unique=False
    )
    op.create_index(
        op.f('ix_answer_deleted_at'), 'answer', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_deleted_at'), table_name='answer')
    op.drop_index(op.f('ix_answer_creator_ip'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_index(op.f('ix_todo_deleted_at'), table_name='todo')
    op.drop_index(op.f('ix_todo_creator_ip'), table_name='todo')
    op.drop_table('todo')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_index(op.f('ix_question_deleted_at'), table_name='question')
    op.drop_index(op.f('ix_question_creator_ip'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
